name: RP2040-Boot2 Compilation action
# Define the trigger event(s)
on: [push]
# Jobs run in parallel by defaults, each runs steps in sequence
jobs:
  # Job Number 1
  test-command:
    runs-on: ubuntu-latest
    steps:
      - name: Test command
        run: echo "This is a place holder until I get the action ready."
