name: RP2040-Boot2 Compilation action
# Define the trigger event(s)
on: [push]
# Jobs run in parallel by defaults, each runs steps in sequence
jobs:
  # Used to compile and build project.
  DevEnv-Install:
    runs-on: ubuntu-latest
    steps:
      # Check out this repo
      - name: Check out this repo
        uses: actions/checkout@v3
      # Installs Arm GNU Toolchain 13.2.rel1
      # https://github.com/marketplace/actions/arm-none-eabi-gcc-gnu-arm-embedded-toolchain
      - name: Install Arm GNU Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.2.Rel1'
      # Install CMake version 3.29.0
      # https://github.com/marketplace/actions/install-latest-cmake
      - name: Install CMake 3.29.0
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.29.0
      # Install Python and GCC
      - name: Install Dependencies
        run: sudo apt install -y build-essential python3 ninja-build
      # See where we are in the VM.
      - run: pwd
      # Run Build and Test script
      # TODO 

