name: RP2040-Boot2 Compilation action
# Define the trigger event(s)
on: [push]
# Jobs run in parallel by defaults, each runs steps in sequence
jobs:
  # Used to compile and build project.
  Build-Compilation-Check:
    runs-on: ubuntu-latest
    steps:
      # Installs Arm GNU Toolchain 13.2.rel1
      # https://github.com/marketplace/actions/arm-none-eabi-gcc-gnu-arm-embedded-toolchain
      - name: Install Arm GNU Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '13.2.Rel1'
      - name: Check Arm GNU Toolchain Install
        run: arm-none-eabi-gcc --version
      # Install CMake version 3.29.0
      # https://github.com/marketplace/actions/install-latest-cmake
      - name: Install CMake 3.29.0
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.29.0
      - name: Check CMake Install
        run: cmake --version
      # Just a test message
      - name: Test command
        run: echo "This is a place holder until I get the action ready."
